{
 "title": "Rhom Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Updates Triggered",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "location_pipeline_updates_triggered"
    }
   ]
  },
  {
   "title": "Activities Fetched",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "location_pipeline_activities_fetched"
    }
   ]
  },
  {
   "title": "Locations Fetched",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "location_pipeline_activity_locations_fetched"
    }
   ]
  },
  {
   "title": "Locations Augmented",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "location_pipeline_locations_augmented"
    }
   ]
  }
 ]
}